image: ${REGISTRY_HOST}/beckhoff/bdpg:v13.3.1

variables:
  GIT_DEPTH: 10

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

docker-image-build:
  image: ${REGISTRY_HOST}/beckhoff/okinak:master
  stage: .pre
  parallel:
    matrix:
      - TARGET_ARCH:
        - amd64
        - arm64
  tags:
    - ${TARGET_ARCH}
    - docker-v2-privileged
  script:
    - okinak build-native --file=Dockerfile

.build:
  stage: build
  image: ${CI_REGISTRY_IMAGE}/build:${CI_COMMIT_REF_SLUG}-${BHF_CI_ARCH}
  timeout: 30m
  tags:
    - docker-v2
    - ${BHF_CI_ARCH}
  before_script:
    # It seems sometimes there are old build files on the runner
    - rm -f ../linux-*.deb
    - export DEBFULLNAME="Beckhoff Automation GmbH & Co. KG"
    - export DEBEMAIL="info@beckhoff.com"
    - cp config-${BHF_CI_ARCH} .config
  artifacts:
    expire_in: 1 week
    when: always
    paths:
      - ./*.deb
      - ./*.debian.tar.xz
      - ./*.dsc
      - ./*.orig.tar.gz

build:
  extends: .build
  parallel:
    matrix:
      - BHF_CI_ARCH:
          - amd64
          - arm64
  script:
    - make -j$(nproc) bindeb-pkg
    # GitLab cannot pickup artifacts from outside of CI_PROJECT_DIR
    - mv ../linux-*${CI_PIPELINE_ID}*.deb ./
    - ./build-meta-package.sh linux-*.deb
    - bdpg push-pipelines linux-*.deb

build-src:
  extends: .build
  variables:
    BHF_CI_ARCH: "arm64"
  tags:
    - docker-v2
    - multiarch
  script:
    - make -j$(nproc) srcdeb-pkg
    - mv ../linux-upstream_*${CI_PIPELINE_ID}* .
    - bdpg push-pipelines linux-*.dsc

test:
  stage: test
  parallel:
    matrix:
      - LINUX_CI_RUN_MANUALLY: "n"
      - LINUX_CI_RUN_MANUALLY: "y"
        BHF_CI_DO_INSTALL: "y"
      - LINUX_CI_RUN_MANUALLY: "y"
        BHF_CI_CYCLICTEST_DURATION: "180m"
        BHF_CI_DO_INSTALL: "y"
        BHF_CI_TEST_LIST: "cyclictest"
  trigger:
    project: beckhoff/test-tcos
    branch: bhf/13/trixie
    strategy: depend
    forward:
      pipeline_variables: true
  variables:
    BHF_CI_PIPELINE_REPOS: "linux/${CI_PIPELINE_ID}"
  rules:
    - if: $BHF_CI_SKIP_TEST == "y"
      when: never
    - if: $LINUX_CI_RUN_MANUALLY == "y"
      when: manual
    - when: on_success

publish:
  stage: .post
  needs: ["build", "build-src"]
  script:
    - bdpg push --skip-changelog-check ./linux-headers-*.deb ./linux-image-*.deb ./linux-*.dsc
  when: manual
