#!/bin/sh
set -e

### vars replaced by templating:
readonly KERNELRELEASE="@KERNELRELEASE@"
readonly HOST_UKI_PATH="@HOST_UKI_PATH@"
readonly PACKAGE="@PACKAGE@"

case "${1}" in
	remove|deconfigure)
		kernel-install remove "${KERNELRELEASE}"
		;;
esac
